### ISSUE TITLE
Can not start service

### ISSUE THREAD

**Issue by pengqinglan** [pengqinglan/PrivateSocks#2]
start script:
```sh
PrivateSocks > log &
```
log out put:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x7ea280, 0xc42000d580)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/root/work/src/github.com/pengqinglan/PrivateSocks/server.go:303 +0x378
```

**Comment by pengqinglan** [comment]
fix at a6e933e8e34ff75d502d5f0a0d1f2c1fc105b8e9
